source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'api_common-methods_Example', :exclusive => true do
  pod "api_common-methods", :path => "../"
end

target 'api_common-methods_Tests', :exclusive => true do
  pod "api_common-methods", :path => "../"

  pod 'FBSnapshotTestCase'
end
